### ISSUE TITLE
Linux Build Failure

### ISSUE THREAD

**Issue by arwhalley** [opensim-org/opensim-gui#1483]
### Steps to reproduce

Install Linux Mint 21.3 which is based on Ubuntu 22.04 (although same failure happened on the latter).
Download https://github.com/opensim-org/opensim-gui/blob/main/scripts/build/opensim-gui-linux-build-script.sh and execute.

### Expected result

Compilation success.

### Actual result

robert@CRAWLER-E10:~$ ./opensim-gui-linux-build-script.sh -j2

...

-do-compile:
    [mkdir] Created dir: /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/build/classes
 [nb-javac] Compiling 870 source files to /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/build/classes
 [nb-javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:74: error: cannot find symbol
 [nb-javac]         opensimSimulationJNI.delete_ReferencePtrCoordinate(swigCPtr);
 [nb-javac]                             ^
 [nb-javac]   symbol:   method delete_ReferencePtrCoordinate(long)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:84: error: cannot find symbol
 [nb-javac]     this(opensimSimulationJNI.new_ReferencePtrCoordinate__SWIG_0(), true);
 [nb-javac]                              ^
 [nb-javac]   symbol:   method new_ReferencePtrCoordinate__SWIG_0()
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:93: error: cannot find symbol
 [nb-javac]     this(opensimSimulationJNI.new_ReferencePtrCoordinate__SWIG_1(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
 [nb-javac]                              ^
 [nb-javac]   symbol:   method new_ReferencePtrCoordinate__SWIG_1(long)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:100: error: cannot find symbol
 [nb-javac]     this(opensimSimulationJNI.new_ReferencePtrCoordinate__SWIG_2(Coordinate.getCPtr(tp), tp), true);
 [nb-javac]                              ^
 [nb-javac]   symbol:   method new_ReferencePtrCoordinate__SWIG_2(long,Coordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:108: error: cannot find symbol
 [nb-javac]     this(opensimSimulationJNI.new_ReferencePtrCoordinate__SWIG_4(ReferencePtrCoordinate.getCPtr(arg0), arg0), true);
 [nb-javac]                              ^
 [nb-javac]   symbol:   method new_ReferencePtrCoordinate__SWIG_4(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:117: error: cannot find symbol
 [nb-javac]     this(opensimSimulationJNI.new_ReferencePtrCoordinate__SWIG_6(mustBeZero), true);
 [nb-javac]                              ^
 [nb-javac]   symbol:   method new_ReferencePtrCoordinate__SWIG_6(int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:124: error: cannot find symbol
 [nb-javac]     long cPtr = opensimSimulationJNI.ReferencePtrCoordinate_get(swigCPtr, this);
 [nb-javac]                                     ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:133: error: cannot find symbol
 [nb-javac]     return new Coordinate(opensimSimulationJNI.ReferencePtrCoordinate_getRef(swigCPtr, this), false);
 [nb-javac]                                               ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getRef(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:141: error: cannot find symbol
 [nb-javac]     long cPtr = opensimSimulationJNI.ReferencePtrCoordinate___deref__(swigCPtr, this);
 [nb-javac]                                     ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate___deref__(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:150: error: cannot find symbol
 [nb-javac]     return new Coordinate(opensimSimulationJNI.ReferencePtrCoordinate___ref__(swigCPtr, this), false);
 [nb-javac]                                               ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate___ref__(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:158: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_reset__SWIG_0(swigCPtr, this, Coordinate.getCPtr(tp), tp);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_reset__SWIG_0(long,ReferencePtrCoordinate,long,Coordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:166: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_reset__SWIG_1(swigCPtr, this);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_reset__SWIG_1(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:174: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_swap(swigCPtr, this, ReferencePtrCoordinate.getCPtr(other), other);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_swap(long,ReferencePtrCoordinate,long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:181: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_empty(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_empty(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:189: error: cannot find symbol
 [nb-javac]     long cPtr = opensimSimulationJNI.ReferencePtrCoordinate_release(swigCPtr, this);
 [nb-javac]                                     ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_release(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:197: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_clear(swigCPtr, this);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_clear(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:201: error: cannot find symbol
 [nb-javac]     long cPtr = opensimSimulationJNI.ReferencePtrCoordinate_clone(swigCPtr, this);
 [nb-javac]                                     ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_clone(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:206: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getConcreteClassName(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getConcreteClassName(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:210: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_default_value__SWIG_0(swigCPtr, this, i);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_default_value__SWIG_0(long,ReferencePtrCoordinate,int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:214: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_default_value__SWIG_1(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_default_value__SWIG_1(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:218: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_default_speed_value__SWIG_0(swigCPtr, this, i);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_default_speed_value__SWIG_0(long,ReferencePtrCoordinate,int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:222: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_default_speed_value__SWIG_1(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_default_speed_value__SWIG_1(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:226: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_range(swigCPtr, this, i);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_range(long,ReferencePtrCoordinate,int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:230: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_clamped__SWIG_0(swigCPtr, this, i);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_clamped__SWIG_0(long,ReferencePtrCoordinate,int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:234: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_clamped__SWIG_1(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_clamped__SWIG_1(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:238: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_locked__SWIG_0(swigCPtr, this, i);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_locked__SWIG_0(long,ReferencePtrCoordinate,int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:242: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_locked__SWIG_1(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_locked__SWIG_1(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:246: error: cannot find symbol
 [nb-javac]     return new Function(opensimSimulationJNI.ReferencePtrCoordinate_get_prescribed_function__SWIG_0(swigCPtr, this, i), false);
 [nb-javac]                                             ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_prescribed_function__SWIG_0(long,ReferencePtrCoordinate,int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:250: error: cannot find symbol
 [nb-javac]     return new Function(opensimSimulationJNI.ReferencePtrCoordinate_get_prescribed_function__SWIG_1(swigCPtr, this), false);
 [nb-javac]                                             ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_prescribed_function__SWIG_1(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:254: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_prescribed__SWIG_0(swigCPtr, this, i);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_prescribed__SWIG_0(long,ReferencePtrCoordinate,int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:258: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_prescribed__SWIG_1(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_prescribed__SWIG_1(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:262: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_is_free_to_satisfy_constraints__SWIG_0(swigCPtr, this, i);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_is_free_to_satisfy_constraints__SWIG_0(long,ReferencePtrCoordinate,int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:266: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_get_is_free_to_satisfy_constraints__SWIG_1(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_get_is_free_to_satisfy_constraints__SWIG_1(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:270: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate__has_output_value_get(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate__has_output_value_get(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:274: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate__has_output_speed_get(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate__has_output_speed_get(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:278: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate__has_output_acceleration_get(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate__has_output_acceleration_get(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:285: error: cannot find symbol
 [nb-javac]     return new Joint(opensimSimulationJNI.ReferencePtrCoordinate_getJoint(swigCPtr, this), false);
 [nb-javac]                                          ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getJoint(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:293: error: cannot find symbol
 [nb-javac]     return Coordinate.MotionType.swigToEnum(opensimSimulationJNI.ReferencePtrCoordinate_getMotionType(swigCPtr, this));
 [nb-javac]                                                                 ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getMotionType(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:300: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getValue(swigCPtr, this, State.getCPtr(s), s);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getValue(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:318: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_setValue__SWIG_0(swigCPtr, this, State.getCPtr(s), s, aValue, enforceContraints);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_setValue__SWIG_0(long,ReferencePtrCoordinate,long,State,double,boolean)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:336: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_setValue__SWIG_1(swigCPtr, this, State.getCPtr(s), s, aValue);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_setValue__SWIG_1(long,ReferencePtrCoordinate,long,State,double)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:343: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getSpeedValue(swigCPtr, this, State.getCPtr(s), s);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getSpeedValue(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:347: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_setSpeedValue(swigCPtr, this, State.getCPtr(s), s, aValue);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_setSpeedValue(long,ReferencePtrCoordinate,long,State,double)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:355: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getSpeedName(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getSpeedName(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:363: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getQDotValue(swigCPtr, this, State.getCPtr(s), s);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getQDotValue(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:371: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getDefaultValue(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getDefaultValue(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:379: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getDefaultSpeedValue(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getDefaultSpeedValue(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:387: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getAccelerationValue(swigCPtr, this, State.getCPtr(s), s);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getAccelerationValue(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:395: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getClamped(swigCPtr, this, State.getCPtr(s), s);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getClamped(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:399: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_setClamped(swigCPtr, this, State.getCPtr(s), s, aClamped);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_setClamped(long,ReferencePtrCoordinate,long,State,boolean)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:406: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getDefaultClamped(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getDefaultClamped(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:413: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getRangeMin(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getRangeMin(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:417: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getRangeMax(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getRangeMax(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:425: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getLocked(swigCPtr, this, State.getCPtr(s), s);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getLocked(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:429: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_setLocked(swigCPtr, this, State.getCPtr(s), s, aLocked);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_setLocked(long,ReferencePtrCoordinate,long,State,boolean)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:436: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getDefaultLocked(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getDefaultLocked(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:444: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_isPrescribed(swigCPtr, this, State.getCPtr(s), s);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_isPrescribed(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:448: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_setIsPrescribed(swigCPtr, this, State.getCPtr(s), s, isPrescribed);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_setIsPrescribed(long,ReferencePtrCoordinate,long,State,boolean)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:455: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getDefaultIsPrescribed(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getDefaultIsPrescribed(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:459: error: cannot find symbol
 [nb-javac]     return new Function(opensimSimulationJNI.ReferencePtrCoordinate_getPrescribedFunction(swigCPtr, this), false);
 [nb-javac]                                             ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getPrescribedFunction(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:468: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_isDependent(swigCPtr, this, State.getCPtr(s), s);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_isDependent(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:475: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_isConstrained(swigCPtr, this, State.getCPtr(s), s);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_isConstrained(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:482: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getMobilizerQIndex(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getMobilizerQIndex(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:486: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getBodyIndex(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getBodyIndex(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:493: error: cannot find symbol
 [nb-javac]     return Coordinate.MotionType.swigToEnum(opensimSimulationJNI.ReferencePtrCoordinate_getUserSpecifiedMotionTypePriorTo40(swigCPtr, this));
 [nb-javac]                                                                 ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getUserSpecifiedMotionTypePriorTo40(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:500: error: cannot find symbol
 [nb-javac]     return new Model(opensimSimulationJNI.ReferencePtrCoordinate_getModel(swigCPtr, this), false);
 [nb-javac]                                          ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getModel(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:507: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_hasModel(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_hasModel(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:514: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_addToSystem(swigCPtr, this, SWIGTYPE_p_SimTK__MultibodySystem.getCPtr(system));
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_addToSystem(long,ReferencePtrCoordinate,long)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:521: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_initStateFromProperties(swigCPtr, this, State.getCPtr(state), state);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_initStateFromProperties(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:589: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_generateDecorations(swigCPtr, this, fixed, ModelDisplayHints.getCPtr(hints), hints, State.getCPtr(state), state, ArrayDecorativeGeometry.getCPtr(appendToThis), appendToThis);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_generateDecorations(long,ReferencePtrCoordinate,boolean,long,ModelDisplayHints,long,State,long,ArrayDecorativeGeometry)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:600: error: cannot find symbol
 [nb-javac]     return new SWIGTYPE_p_SimTK__MultibodySystem(opensimSimulationJNI.ReferencePtrCoordinate_getSystem(swigCPtr, this), false);
 [nb-javac]                                                                      ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getSystem(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:609: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_hasSystem(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_hasSystem(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:617: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_isComponentInOwnershipTree(swigCPtr, this, Component.getCPtr(component), component);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_isComponentInOwnershipTree(long,ReferencePtrCoordinate,long,Component)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:630: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getAbsolutePathString(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getAbsolutePathString(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:643: error: cannot find symbol
 [nb-javac]     return new ComponentPath(opensimSimulationJNI.ReferencePtrCoordinate_getAbsolutePath(swigCPtr, this), true);
 [nb-javac]                                                  ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getAbsolutePath(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:651: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getRelativePathString(swigCPtr, this, Component.getCPtr(wrt), wrt);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getRelativePathString(long,ReferencePtrCoordinate,long,Component)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:659: error: cannot find symbol
 [nb-javac]     return new ComponentPath(opensimSimulationJNI.ReferencePtrCoordinate_getRelativePath(swigCPtr, this, Component.getCPtr(wrt), wrt), true);
 [nb-javac]                                                  ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getRelativePath(long,ReferencePtrCoordinate,long,Component)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:672: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_hasComponent(swigCPtr, this, pathname);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_hasComponent(long,ReferencePtrCoordinate,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:693: error: cannot find symbol
 [nb-javac]     return new Component(opensimSimulationJNI.ReferencePtrCoordinate_getComponent(swigCPtr, this, pathname), false);
 [nb-javac]                                              ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getComponent(long,ReferencePtrCoordinate,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:717: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_printComponentsMatching(swigCPtr, this, substring);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_printComponentsMatching(long,ReferencePtrCoordinate,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:727: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getNumStateVariables(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getNumStateVariables(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:737: error: cannot find symbol
 [nb-javac]     return new ArrayStr(opensimSimulationJNI.ReferencePtrCoordinate_getStateVariableNames(swigCPtr, this), true);
 [nb-javac]                                             ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getStateVariableNames(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:744: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getNumSockets(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getNumSockets(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:757: error: cannot find symbol
 [nb-javac]     return new StdVectorString(opensimSimulationJNI.ReferencePtrCoordinate_getSocketNames(swigCPtr, this), true);
 [nb-javac]                                                    ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getSocketNames(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:786: error: cannot find symbol
 [nb-javac]     return new OpenSimObject(opensimSimulationJNI.ReferencePtrCoordinate_getConnectee(swigCPtr, this, name), false);
 [nb-javac]                                                  ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getConnectee(long,ReferencePtrCoordinate,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:790: error: cannot find symbol
 [nb-javac]     return new AbstractSocket(opensimSimulationJNI.ReferencePtrCoordinate_getSocket(swigCPtr, this, name), false);
 [nb-javac]                                                   ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getSocket(long,ReferencePtrCoordinate,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:797: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getNumInputs(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getNumInputs(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:804: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getNumOutputs(swigCPtr, this);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getNumOutputs(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:812: error: cannot find symbol
 [nb-javac]     return new StdVectorString(opensimSimulationJNI.ReferencePtrCoordinate_getInputNames(swigCPtr, this), true);
 [nb-javac]                                                    ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getInputNames(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:820: error: cannot find symbol
 [nb-javac]     return new StdVectorString(opensimSimulationJNI.ReferencePtrCoordinate_getOutputNames(swigCPtr, this), true);
 [nb-javac]                                                    ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getOutputNames(long,ReferencePtrCoordinate)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:839: error: cannot find symbol
 [nb-javac]     return new AbstractInput(opensimSimulationJNI.ReferencePtrCoordinate_getInput(swigCPtr, this, name), false);
 [nb-javac]                                                  ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getInput(long,ReferencePtrCoordinate,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:854: error: cannot find symbol
 [nb-javac]     return new AbstractOutput(opensimSimulationJNI.ReferencePtrCoordinate_getOutput(swigCPtr, this, name), false);
 [nb-javac]                                                   ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getOutput(long,ReferencePtrCoordinate,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:867: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getModelingOption(swigCPtr, this, State.getCPtr(state), state, name);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getModelingOption(long,ReferencePtrCoordinate,long,State,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:881: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_setModelingOption(swigCPtr, this, State.getCPtr(state), state, name, flag);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_setModelingOption(long,ReferencePtrCoordinate,long,State,String,int)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:900: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getStateVariableValue__SWIG_0(swigCPtr, this, State.getCPtr(state), state, name);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getStateVariableValue__SWIG_0(long,ReferencePtrCoordinate,long,State,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:920: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getStateVariableValue__SWIG_1(swigCPtr, this, State.getCPtr(state), state, ComponentPath.getCPtr(path), path);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getStateVariableValue__SWIG_1(long,ReferencePtrCoordinate,long,State,long,ComponentPath)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:933: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_setStateVariableValue(swigCPtr, this, State.getCPtr(state), state, name, value);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_setStateVariableValue(long,ReferencePtrCoordinate,long,State,String,double)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:947: error: cannot find symbol
 [nb-javac]     return new Vector(opensimSimulationJNI.ReferencePtrCoordinate_getStateVariableValues(swigCPtr, this, State.getCPtr(state), state), true);
 [nb-javac]                                           ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getStateVariableValues(long,ReferencePtrCoordinate,long,State)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:968: error: cannot find symbol
 [nb-javac]     opensimSimulationJNI.ReferencePtrCoordinate_setStateVariableValues(swigCPtr, this, State.getCPtr(state), state, Vector.getCPtr(values), values);
 [nb-javac]                         ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_setStateVariableValues(long,ReferencePtrCoordinate,long,State,long,Vector)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] /home/robert/opensim-workspace/opensim-gui-source/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java:980: error: cannot find symbol
 [nb-javac]     return opensimSimulationJNI.ReferencePtrCoordinate_getStateVariableDerivativeValue(swigCPtr, this, State.getCPtr(state), state, name);
 [nb-javac]                                ^
 [nb-javac]   symbol:   method ReferencePtrCoordinate_getStateVariableDerivativeValue(long,ReferencePtrCoordinate,long,State,String)
 [nb-javac]   location: class opensimSimulationJNI
 [nb-javac] 100 errors
 [nb-javac] 1 warning

BUILD FAILED
/home/robert/netbeans-12.3/netbeans/harness/suite.xml:163: The following error occurred while executing this line:
/home/robert/netbeans-12.3/netbeans/harness/common.xml:206: Compile failed; see the compiler error output for details.

Total time: 6 seconds
make[3]: *** [Gui/opensim/CMakeFiles/PrepareInstaller.dir/build.make:71: Gui/opensim/CMakeFiles/PrepareInstaller] Error 1
make[2]: *** [CMakeFiles/Makefile2:210: Gui/opensim/CMakeFiles/PrepareInstaller.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:217: Gui/opensim/CMakeFiles/PrepareInstaller.dir/rule] Error 2
make: *** [Makefile:176: PrepareInstaller] Error 2
robert@CRAWLER-E10:~$ 

### Environment and GUI version

As installed by the build script.

**Comment by johanna4711** [comment]
+1

Can confirm using PopOS (based on Ubuntu 22.04). Checked with original Ubuntu 22.04 (both fresh clean installations).

**Comment by aymanhab** [comment]
Thanks for reporting, this was due to a stale file that was removed on the opensim 4.5 branch. The patch was merged and will report here as soon as ci is finished building.

**Comment by aymanhab** [comment]
The issue has been fixed as evident by the latest ci build here https://github.com/opensim-org/opensim-gui/actions

**Comment by arwhalley** [comment]
Many thanks, Ayman, and the whole team. What marvellous, rapid response! Can confirm that the build works on Linux Mint 21.3!

**Comment by mkhoshle** [comment]
@aymanhab I also have the same issue. Could you please provide the link to a version that can be built?

**Comment by arwhalley** [comment]
Hi Mahzad,

I simply cleaned out all caches, source and build directories and then
downloaded the build script from
https://github.com/opensim-org/opensim-gui/blob/main/scripts/build/opensim-gui-linux-build-script.sh,
and ran it. It retrieves all the source code repositories as it goes, and,
for me, just ran to a successful conclusion, once Ayman had made his latest
changes.

Hope that helps,

Best wishes,

Rob

**Comment by mkhoshle** [comment]
Hi @arwhalley 

Thanks for the quick response. I did the same but the build still fails and I get the same error. And I am not sure what I am supposed to do to resolve this. Any thought?

Thanks

**Comment by arwhalley** [comment]
Hi Mahzad,

What OS are you using and what errors do you see? I omitted to mention
that, since I'm using Linux Mint 21.3, I had to edit the /etc/lsb_release
and /etc/os_release files to "pretend" that they were genuine Ubuntu 22.04.
Apart from that, I did have to remove everything, including hidden
configuration directories and files, the version of netbeans, and swig that
the script installs, and all my JDK installations. If you are using an
Ubuntu based distro you could check what version of Java is set up as the
default because the script installs and expects to use openjdk-8.

Apart from that, If you are still getting the missing symbols errors,
connected with opensimSimulationJNI then you'll have to get back to Ayman
Habib or someone from the OpenSim development team.

Good luck,

Rob

**Comment by aymanhab** [comment]
The nightly build failed due to a more recent change in opensim-core, I'm investigating but you may want to go back a few days ago in opensim-core until I investigate and possibly update the GUI code base. Thank you

**Comment by mkhoshle** [comment]
@aymanhab I use x86-64 GNU/Linux Release 20.04. 

About Java here is the version that I am using:
```
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)
```

I don't know what the problem is. Based on the build instructions, it seems it has been tested on ubuntu 18.04, 20.04, 22.04.

**Comment by aymanhab** [comment]
@mkhoshle the errors you see are the same on the nightly build due to an opensim-core commit that changed the ArrayDouble interface inadvertently two days ago. While I can update the GUI code to fix, I'm trying to assess if this is an issue that will be seen by users and if so fix it on the opensim-core side vs. make the GUI code change.  
We use java jdk 1.8 because some sections of the code base have not been upgraded to later java jdk. Hope this helps.

**Comment by mkhoshle** [comment]
@aymanhab I have built the OpenSim core successfully. I wanted to build the GUI so that I could use it for visualization. Does building opensim-core build the GUI as well? Or I assume they need to be built separately.

**Comment by arwhalley** [comment]
Hi Mahzad,

The build script at
https://github.com/opensim-org/opensim-gui/blob/main/scripts/build/opensim-gui-linux-build-script.sh
builds both the core and the GUI together. You can build the core
separately by cloning the repositories and using cmake, and that works fine
on Ubuntu 22.04 but won't get you a GUI. I have managed, in the past, to
build the GUI as well, cloning the repository and using cmake, but the
build script is so much easier.

The build script takes parameters that allow you to specify the version of
core and GUI that you wish to build. I would try Ayman's suggestion of
using a version of core from a few days ago, since that worked for me.

Best wishes,

Rob

**Comment by mkhoshle** [comment]
@arwhalley Can you put the link to the version that you installed here? I tried this several times and I was not successful. Maybe I am using the wrong link or version. I am not really sure what I am doing wrong.

**Comment by aymanhab** [comment]
Build has been fixed on the opensim-core side, latest github ci actions are successful, please refresh and retry. Thanks for reporting
 https://github.com/opensim-org/opensim-gui/actions

**Comment by mkhoshle** [comment]
Hi @aymanhab @arwhalley Thanks for the feedback. I installed using the updated version and the build was successful. After it I launched Opensim - Apache NetBeans IDE 12.3 and Browsed to one of its OpenSim sub-folder's named Gui/ and then open the "project" opensim.  Clicked on the green arrow button (run project button) to automatically compile all the source and launch the OpenSim GUI. I get the following errors:

```
ant -f /home/mkhoshle/Desktop/opensim-gui/Gui/opensim/scriptingShell -Dcontinue.after.failing.tests=true run
taskdefs:
common-init:
projectized-common.basic-init:
basic-init:
files-init:
nbm-license-init:
build-init:
Scanning for modules in /home/mkhoshle/netbeans-12.3/netbeans/ide
Scanning for modules in /home/mkhoshle/netbeans-12.3/netbeans/platform
Scanning for modules in suite /home/mkhoshle/Desktop/opensim-gui/Gui/opensim
/home/mkhoshle/netbeans-12.3/netbeans/harness/build.xml:150: 
java.io.IOException: No such module /home/mkhoshle/Desktop/opensim-gui/opensim-visualizer/jxbrowser referred to from /home/mkhoshle/Desktop/opensim-gui/Gui/opensim
	at org.netbeans.nbbuild.ModuleListParser.doScanSuite(ModuleListParser.java:676)
	at org.netbeans.nbbuild.ModuleListParser.scanSuiteSources(ModuleListParser.java:650)
	at org.netbeans.nbbuild.ModuleListParser.<init>(ModuleListParser.java:764)
	at org.netbeans.nbbuild.ParseProjectXml.execute(ParseProjectXml.java:426)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:261)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:574)
	at org.netbeans.core.execution.RunClassThread.doRun(RunClassThread.java:132)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:81)
BUILD FAILED (total time: 0 seconds)
```
it seems that jxbrowser module is missing. But I am not sure why. Is not the .sh script supposed to take care of everything? What do I need to do? Any thoughs?

Thank you

**Comment by arwhalley** [comment]
Hi Mahzad,
Do you have a specific reason for wanting to build / run within Netbeans?
The build script should have installed the OpenSim application (in
/opt/opensim-gui by default). The bin directory should have an opensim
binary that you can execute directly.
Best wishes,
Rob

**Comment by mkhoshle** [comment]
@arwhalley I was following the instructions [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Building+the+GUI). I am not able to see any bin directory inside `opensim-gui`.  I can see the opensim icon whithin the installed applications but when I click on it, the application does not get started.

**Comment by mkhoshle** [comment]
@arwhalley Yes I have those:
```
(base) mkhoshle@tapetum:~/Desktop/opensim-gui$ ls /opt/opensim-gui
bin  cmake  doc  etc  Geometry  ide  INSTALL  LICENSE.txt  NOTICE.txt  opensim  opensim.desktop  OpenSimLogoWhiteNoText.png  platform  Resources.zip  sdk  third_party_license_texts  threejs
(base) mkhoshle@tapetum:~/Desktop/opensim-gui$ ls /opt/opensim-gui/bin/
opensense  opensim  opensim-cmd  opensim-install-command-line.sh

```
What do I need to do to run opensim then?
because trying opensim in terminal gives me the following message:
```
(base) mkhoshle@tapetum:~/Desktop/opensim-gui$ opensim

Command 'opensim' not found, did you mean:

  command 'opensm' from deb opensm (3.3.21-2)

Try: sudo apt install <deb name>

```

**Comment by arwhalley** [comment]
Hi Mahzad,

I'm guessing that you are fairly new to Linux and I can't really teach you
the operating system, but in order to execute a program it must be in a
directory that is in the PATH environment variable search list. If it needs
libraries, then they need to be on the LD_LIBRARY_PATH environment
variable search list.

However, if you want the full GUI experience, and are using a Gnome based
desktop derivative of some sort, you can create a launcher file -
~/.local/share/applications/opensim.desktop with contents like:

[Desktop Entry]
Version=1.0
Type=Application
Name=OpenSim
Comment=OpenSim is an open source software for neuromusculoskeletal
modeling, simulation and analysis.
PATH=/opt/opensim-gui
Exec=env -u GNOME_DESKTOP_SESSION_ID -C /opt/opensim-gui
/opt/opensim-gui/bin/opensim
Icon=/opt/opensim-gui/OpenSimLogoWhiteNoText.png
Terminal=false
Categories=Science;Education

I hope that helps,

 Rob

**Comment by arwhalley** [comment]
Hi Mahzad,

In addition to my last email, you can always simply execute:

cd /opt/opensim-gui
bin/opensim

That should get you a working GUI - but to integrate it properly into your
work environment, you'll need to ask colleagues, do some reading etc.

Good luck,

Rob

**Comment by arwhalley** [comment]
Hi Mahzad,

I'm so glad it's now working. Well done.

Best wishes,

Rob

**Comment by arwhalley** [comment]
Hi Ayman,

OpenSim GUI is all up and running, and your very quick response and fix was
really appreciated. Since then I have discovered another problem, and
posted an issue on the opensim-core forum, but as yet, no one has taken it
up.

I am running Mint 21.3 and / or a fresh Ubuntu 22.04, it makes no
difference. That means I'm using Python3.10, and if I try any of the script
examples from
opensim-workspace/opensim-core-source/Bindings/Python/examples (such as
build_simple_arm_model.py) the visualizer throws an exception complaining
of a broken pipe. This is also true of anything I try involving the
visualizer, in an interactive Python shell. I have also tried a virtual
environment running Python3.8 but with the same outcome.

The dual pendulum C++ example compiles and runs reliably every time, so it
doesn't seem directly related to my environment and I am wondering if there
is a mistake somewhere in the SWIG wrappers?

I really need the Python API to work, and I wondered if you had any
suggestions as to things that I could investigate?

Best wishes,

Rob Whalley

**Comment by aymanhab** [comment]
@arwhalley there're a lot of options for setting python environment, using the manual configuration to set up LD_LIBRARY_PATH is messy and error prone and relies on using the same python version for building and running. Alternatively off-the-shelf installation with conda is safer but is typically only available for public releases. Can you clarify your python environment? Would be good to have a separate issue with the details so the discussion is not buried in this closed/old issue. Thank you

**Comment by arwhalley** [comment]
Hi Ayman,

I have already raised Issue #3718 on the opensim-core for this.

I contacted you directly, because no one has responded to that, and I need
to try and get this working again. I'm working on Mint 21.3, or a fresh
Ubuntu 22.04 installation, and have built both the opensim-gui and the
opensim-core using the build script available for the former. I have
created a Python virtual environment using virtualenvwrapper and installed
the opensim module from /opt/opensim-gui/sdk/Python into it. Then, using
that virtual environment and in the
opensim-workspace/opensim-core-source/Bindings/Python/examples directory, I
open a shell and execute "python build_simple_arm_model.py". The visualizer
window opens momentarily, and then the script crashes with a segmentation
fault. The stack dumps are in issue #3718. The native Python in Ubuntu
22.04 is Python3.10, but I have also installed and tried Python3.8. Both
cause the same problem.

 The C++ double pendulum example I have compiled and that executes without
error.

I hope that helps, but I'll try and expand more if you need me to.

Many thanks,

Rob Whalley
