### ISSUE TITLE
Muscle should not be open cylinders

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#581]
### Steps to reproduce
Open a model and look at the end of a muscle.

### Expected result
Muscle is a cylinder with closed ends.

### Actual result
Muscle is a straw. This issue was already raised in #139, which was closed (the Issue was closed, not the muscle cylinder). If not deemed important, perhaps this Issue can remain open, filed under the "Future Release" milestone?

![](https://user-images.githubusercontent.com/4203505/37240729-3a57f430-2404-11e8-8f2f-ad15e27def2b.png)

### Environment and GUI version
AppVeyor artifact OpenSim-e7831221-2018-03-06.zip

**Comment by jenhicks** [comment]
@aymanhab Can you comment on this one? I think the other issue was closed because the issues in the original checklist were completed.

**Comment by aymanhab** [comment]
Flat caps should be easy to put in and at very little cost to rendering time, Circular caps a re a bit more involved and likely should wait till after 4.0 unless I have volunteers. After flatcap is inplace I can describe what it takes.

**Comment by jenhicks** [comment]
Thanks ... I will edit the title of this a little and put in the 4.0 milestone.

**Comment by aseth1** [comment]
@aymanhab we tried flat caps for ISB last year and they did not work out as expected. We ended up reverting to open cylinders since that was the best we could do in the short-term then. Since you need path points to be editable, I would just make them spheres of the same color and radius as the muscle.

**Comment by tkuchida** [comment]
I managed to cap the ends of the muscles with spheres. It's a pretty big hack at the moment (which should say a lot coming from me :wink:) but I think it could be implemented cleanly without too much additional work. Happy to discuss.

![](https://user-images.githubusercontent.com/4203505/39688182-66f398d2-5186-11e8-937f-7a89b0eaf914.jpg)

**Comment by aymanhab** [comment]
Looking great, i was planning to address this as part of the pathpoint
editing issue on my list, would love to see how yiur solution works, any
overhead incurred during viewing, animation, color changes etc. Let's
discuss in person today.

**Comment by tkuchida** [comment]
Thanks. I didn't know you were working on it. I can't assess impact on performance because the AppVeyor artifact I hacked didn't play smoothly to begin with. I think the most elegant solution would be to draw hemispheres with the same number of slices as the muscle skin and merge the meshes---but it's much simpler to just draw spheres at the endpoints. Not sure whether you want to implement via JSON instructions or entirely on the JavaScript side as I have done.

**Comment by aymanhab** [comment]
Fixed on branch https://github.com/opensim-org/opensim-gui/tree/visual_path_edit

**Comment by aymanhab** [comment]
![opensim_snapshot_caps](https://user-images.githubusercontent.com/3972208/40387571-fa191910-5dc1-11e8-83f4-d8c326850b75.png)

**Comment by tkuchida** [comment]
Looks nice! There's a bit of Z-fighting, but that can be addressed (perhaps in 4.1) by rendering the model plus local part of the floor with tighter clipping planes.

**Comment by aseth1** [comment]
As of OpenSim 1e476f2-2018-06-13 muscles now draw as open tubes again. It is still present in OpenSim 461c0df-2018-06-22. Look terrible IMHO and I don't recall the team decision agreeing to bring it back.

<img width="763" alt="screen shot 2018-06-25 at 2 44 00 pm" src="https://user-images.githubusercontent.com/6494122/41877512-588bbdd4-7886-11e8-8c3e-4cbaddef53ab.png">
