### ISSUE TITLE
I can delete the Sun!

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#698]
### Steps to reproduce
Open model, open scene ligh, expand floor dropdown, click in 'Height' text box, hit backspace on keyboard.

### Expected result
I can delete the numbers in the text box

### Actual result
I get the rush of a Supervillian by deleting the Sun! 

![sunlight](https://user-images.githubusercontent.com/5296507/39537615-fcb09000-4dee-11e8-90ef-2fdd841a9667.gif)

### Environment and GUI version
W10
opensim-04-30-2018

**Comment by aymanhab** [comment]
Actually you can't, you can just move it underground! Hope that keeps your Supervillian spirits up

**Comment by aymanhab** [comment]
Fixed by PR in threejs repo. Will appear in next threejs upgrade

**Comment by jimmyDunne** [comment]
I'm not sure how to test this. It looks like the ability to view the light and move it is now gone! Was this intentional? Now, under the lighting menu, there are only text boxes that do something (that is unclear) to the lighting.

**Comment by aymanhab** [comment]
@jimmyDunne this was part of the plan to make the placement of light more reproducible so you see numbers for x,y,z of scene light. It doesn't help that you can't see the light source itself 😃 I'm working on a compromise and appreciate your input, so drop by when you have a chance to discuss.

**Comment by tkuchida** [comment]
I looked at this as well. The shadow doesn't change when the X/Y/Z fields are edited. I think we need to be able to move the light that casts the shadow in case the shadow gets cut off (#477):

![](https://user-images.githubusercontent.com/4203505/40077032-4fb9c42e-5835-11e8-936f-4caf14d28589.png)
75fdf108-2018-05-11

**Comment by aseth1** [comment]
Following-up on @tkuchida since this issue remains in **Needs Verifying**.
The lighting and shadows are inconsistent with the shading of display geometry.
![image](https://user-images.githubusercontent.com/6494122/40325876-2889e034-5cf2-11e8-86c3-db33fb9170c2.png)

Furthermore, the lighting is not persistent and if I tumble the view in the slightest it returns to what it was previously but none of the lighting values change!
![image](https://user-images.githubusercontent.com/6494122/40326013-a44026d4-5cf2-11e8-830e-a50c78efcbde.png)

More disappointing, however, is the inability to graphically move the light source in the 3D view and see the shadows move. Ideally the position values in the text fields would update and the user could store them as presets. 
Interestingly saving the lighting values as a preset and selecting it from the pull down list (after selecting the default) does restore the lighting (e.g. Sunset below) that was lost while tumbling:
![image](https://user-images.githubusercontent.com/6494122/40326372-d810814c-5cf3-11e8-984e-0d5ced81a73d.png)

In the strictest sense the issue is "fixed" since light-source cannot be deleted, but from a usability standpoint the functionality remains broken.

**Comment by aymanhab** [comment]
Latest build restores the ability to move light source graphically without the ability to delete it. Please verify @aseth1 Thanks

**Comment by aseth1** [comment]
It is nice to graphically move it quickly to the neighborhood you want it in, but also nice to have the fields to then dial it in.  We also lost control of the intensity of the scene light. 
Cool! The shadow is now on the correct side.

**Comment by aseth1** [comment]
![image](https://user-images.githubusercontent.com/6494122/40521060-8130d0ce-5f7e-11e8-81f0-4dd6f448fd90.png)

There is some weird "fuzzy" artifact with the shadow that is pose dependent.

![image](https://user-images.githubusercontent.com/6494122/40521086-a05d4ffe-5f7e-11e8-95bd-787119bbda8a.png)

**Comment by tkuchida** [comment]
I think the fuzziness is the same issue I just fixed locally (caused by a limited shadow map size). I've increased `dirLight.shadow.mapSize.width` and `dirLight.shadow.mapSize.height` to get rid of artifacts like this.
